apiVersion: v1
kind: Pod
metadata:
  name: dataset-uploader
spec:
  containers:
  - name: uploader
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    volumeMounts:
    - mountPath: /data
      name: resnet-storage
  volumes:
  - name: resnet-storage
    persistentVolumeClaim:
      claimName: resnet-data-vol
